[package]
name = "random_note_sequence"
version = "0.1.0"
authors = ["addy-go <addy.gabriel.voice@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
